services:
  grande-bot:
    build: .
    container_name: grande_bot
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - USER_ID=${USER_ID}
      - TARGET_GROUP_ID=${TARGET_GROUP_ID}
      - TARGET_GROUP_USERNAME=${TARGET_GROUP_USERNAME}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR}
      - ENABLE_ADVANCED_VIDEO_PROCESSING=${ENABLE_ADVANCED_VIDEO_PROCESSING}
      - VIDEO_CLIP_DURATION=${VIDEO_CLIP_DURATION}
      - VIDEO_CLIP_START_OFFSET=${VIDEO_CLIP_START_OFFSET}
      - VIDEO_CLEANUP_FILES=${VIDEO_CLEANUP_FILES}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ${DOWNLOAD_DIR}:/app/downloads
    networks:
      - grande-bot-net

networks:
  grande-bot-net:
    driver: bridge